package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.ListPicker;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.PhoneCall;
import com.google.appinventor.components.runtime.Texting;
import com.google.appinventor.components.runtime.BluetoothClient;
import com.google.appinventor.components.runtime.Web;
import com.google.appinventor.components.runtime.Clock;
import com.google.appinventor.components.runtime.ActivityStarter;
class Screen1 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement 模式切換;
  private Button 開發者模式;
  private Button 使用者模式;
  private HorizontalArrangement 藍芽緊急;
  private VerticalArrangement 垂直配置4;
  private Label 藍芽連線;
  private HorizontalArrangement 水平配置4;
  private ListPicker 配對裝置;
  private Button 解除配對;
  private VerticalArrangement 垂直配置5;
  private Label 緊急呼叫;
  private HorizontalArrangement 水平配置5;
  private Button 手機;
  private Button 簡訊;
  private TableArrangement 更改通報電話號碼;
  private TextBox 文字輸入盒1;
  private Button 確定;
  private Button 取消;
  private Label 請輸入號碼：;
  private VerticalArrangement 室內溫溼度;
  private Label 目前室內溫濕度;
  private TableArrangement 表格配置2;
  private Label 目前溫度：;
  private Label 目前濕度：;
  private TextBox 濕度數值;
  private TextBox 溫度數值;
  private TableArrangement UVIAQI;
  private Label 周遭環境空氣品質指數;
  private Label 週遭環境紫外線指數;
  private VerticalArrangement 垂直配置1;
  private Label 縣市名稱U;
  private Label UVI;
  private Label 紫外線等級;
  private ListPicker 選擇觀測站U;
  private Label 經度U;
  private Label 緯度U;
  private Button 開啟Google地圖U;
  private VerticalArrangement 垂直配置2;
  private Label 縣市名稱A;
  private Label AQI;
  private Label 空氣品質等級;
  private ListPicker 選擇觀測站A;
  private Label 經度A;
  private Label 緯度A;
  private Button 開啟Google地圖A;
  private TableArrangement user表格;
  private VerticalArrangement USER溫度;
  private Label 室內溫度user;
  private Label 溫度數值User;
  private Label 溫度敘述User;
  private VerticalArrangement USERaqi;
  private Label AQI地區;
  private Label AQI等級User;
  private Label AQI敘述User;
  private VerticalArrangement USERuvi;
  private Label UVI地區;
  private Label UVI等級User;
  private Label UVI敘述User;
  private VerticalArrangement USER氣體;
  private Label 有害氣體偵測;
  private Label 有害氣體狀態;
  private VerticalArrangement USER地震;
  private Label 地震偵測;
  private Label 地震狀態;
  private VerticalArrangement USER濕度;
  private Label 室內濕度user;
  private Label 濕度數值User;
  private Label 濕度敘述User;
  private Label 讀取資料;
  private PhoneCall 電話撥號器1;
  private Texting 簡訊1;
  private BluetoothClient 藍牙客戶端1;
  private Web GoogleForm;
  private Clock 計時器1;
  private Web webUVI;
  private ActivityStarter Activity開啟地圖;
  private Web webAQI;
  private Web GoogleFormE;
  protected void $define() {
    this.AlignHorizontal(3);
    this.AppName("PhoneCall_Ver3.0");
    this.Icon("icon.png");
    this.Scrollable(true);
    this.Title("PhoneCall_Ver3.0");
    模式切換 = new HorizontalArrangement(this);
    模式切換.AlignHorizontal(3);
    開發者模式 = new Button(模式切換);
    開發者模式.BackgroundColor(0xFFFF0000);
    開發者模式.FontBold(true);
    開發者模式.Text("開發者模式");
    開發者模式.TextColor(0xFFFFFFFF);
    使用者模式 = new Button(模式切換);
    使用者模式.BackgroundColor(0xFF00FF00);
    使用者模式.FontBold(true);
    使用者模式.Text("使用者模式");
    使用者模式.TextColor(0xFFFFFFFF);
    藍芽緊急 = new HorizontalArrangement(this);
    藍芽緊急.AlignHorizontal(3);
    藍芽緊急.BackgroundColor(0xFFFFFFFF);
    垂直配置4 = new VerticalArrangement(藍芽緊急);
    垂直配置4.AlignHorizontal(3);
    垂直配置4.AlignVertical(2);
    垂直配置4.BackgroundColor(0xFFFFFFFF);
    垂直配置4.Width(-1050);
    藍芽連線 = new Label(垂直配置4);
    藍芽連線.FontBold(true);
    藍芽連線.FontSize(30);
    藍芽連線.Text("藍芽連線");
    藍芽連線.TextColor(0xFF0000FF);
    水平配置4 = new HorizontalArrangement(垂直配置4);
    水平配置4.AlignHorizontal(3);
    水平配置4.AlignVertical(2);
    水平配置4.BackgroundColor(0xFFFFFFFF);
    水平配置4.Width(-1050);
    配對裝置 = new ListPicker(水平配置4);
    配對裝置.BackgroundColor(0xFF0000FF);
    配對裝置.FontBold(true);
    配對裝置.FontSize(12);
    配對裝置.Text("配對裝置");
    配對裝置.TextColor(0xFFFFFFFF);
    解除配對 = new Button(水平配置4);
    解除配對.BackgroundColor(0xFF0000FF);
    解除配對.FontBold(true);
    解除配對.FontSize(12);
    解除配對.Text("解除配對");
    解除配對.TextColor(0xFFFFFFFF);
    垂直配置5 = new VerticalArrangement(藍芽緊急);
    垂直配置5.AlignHorizontal(3);
    垂直配置5.AlignVertical(2);
    垂直配置5.BackgroundColor(0xFFFFFFFF);
    垂直配置5.Width(-1050);
    緊急呼叫 = new Label(垂直配置5);
    緊急呼叫.FontBold(true);
    緊急呼叫.FontSize(30);
    緊急呼叫.Text("緊急呼叫");
    緊急呼叫.TextColor(0xFFFF0000);
    水平配置5 = new HorizontalArrangement(垂直配置5);
    水平配置5.AlignHorizontal(3);
    水平配置5.AlignVertical(2);
    水平配置5.BackgroundColor(0xFFFFFFFF);
    水平配置5.Width(-1050);
    手機 = new Button(水平配置5);
    手機.BackgroundColor(0xFFFF0000);
    手機.FontBold(true);
    手機.Text(" 手機 ");
    手機.TextColor(0xFFFFFFFF);
    簡訊 = new Button(水平配置5);
    簡訊.BackgroundColor(0xFFFF0000);
    簡訊.FontBold(true);
    簡訊.Text(" 簡訊 ");
    簡訊.TextColor(0xFFFFFFFF);
    更改通報電話號碼 = new TableArrangement(this);
    更改通報電話號碼.Width(LENGTH_FILL_PARENT);
    文字輸入盒1 = new TextBox(更改通報電話號碼);
    文字輸入盒1.Column(1);
    文字輸入盒1.Width(-1050);
    文字輸入盒1.Row(0);
    確定 = new Button(更改通報電話號碼);
    確定.Column(0);
    確定.FontBold(true);
    確定.FontSize(20);
    確定.Width(-1050);
    確定.Row(1);
    確定.Text("確定");
    取消 = new Button(更改通報電話號碼);
    取消.Column(1);
    取消.FontBold(true);
    取消.FontSize(20);
    取消.Width(-1050);
    取消.Row(1);
    取消.Text("取消");
    請輸入號碼： = new Label(更改通報電話號碼);
    請輸入號碼：.Column(0);
    請輸入號碼：.FontBold(true);
    請輸入號碼：.FontSize(12);
    請輸入號碼：.Width(-1050);
    請輸入號碼：.Row(0);
    請輸入號碼：.Text("更改緊急通報電話號碼：");
    請輸入號碼：.TextColor(0xFFFF0000);
    室內溫溼度 = new VerticalArrangement(this);
    室內溫溼度.AlignHorizontal(3);
    室內溫溼度.AlignVertical(2);
    室內溫溼度.Width(LENGTH_FILL_PARENT);
    目前室內溫濕度 = new Label(室內溫溼度);
    目前室內溫濕度.FontBold(true);
    目前室內溫濕度.FontSize(20);
    目前室內溫濕度.Width(LENGTH_FILL_PARENT);
    目前室內溫濕度.Text("室內溫濕度：");
    目前室內溫濕度.TextColor(0xFFFF00FF);
    表格配置2 = new TableArrangement(室內溫溼度);
    目前溫度： = new Label(表格配置2);
    目前溫度：.BackgroundColor(0xFFFF00FF);
    目前溫度：.Column(0);
    目前溫度：.FontBold(true);
    目前溫度：.FontSize(20);
    目前溫度：.Width(LENGTH_FILL_PARENT);
    目前溫度：.Row(0);
    目前溫度：.Text("目前溫度：");
    目前溫度：.TextColor(0xFFFFFFFF);
    目前濕度： = new Label(表格配置2);
    目前濕度：.BackgroundColor(0xFFFF00FF);
    目前濕度：.Column(0);
    目前濕度：.FontBold(true);
    目前濕度：.FontSize(20);
    目前濕度：.Width(LENGTH_FILL_PARENT);
    目前濕度：.Row(1);
    目前濕度：.Text("目前濕度：");
    目前濕度：.TextColor(0xFFFFFFFF);
    濕度數值 = new TextBox(表格配置2);
    濕度數值.Column(1);
    濕度數值.Hint("正在讀取");
    濕度數值.Row(1);
    溫度數值 = new TextBox(表格配置2);
    溫度數值.Column(1);
    溫度數值.Hint("正在讀取");
    溫度數值.Row(0);
    UVIAQI = new TableArrangement(this);
    UVIAQI.Width(LENGTH_FILL_PARENT);
    周遭環境空氣品質指數 = new Label(UVIAQI);
    周遭環境空氣品質指數.Column(1);
    周遭環境空氣品質指數.FontBold(true);
    周遭環境空氣品質指數.FontSize(24);
    周遭環境空氣品質指數.Width(-1050);
    周遭環境空氣品質指數.Row(0);
    周遭環境空氣品質指數.Text("空氣品質指數");
    周遭環境空氣品質指數.TextColor(0xFF00C715);
    週遭環境紫外線指數 = new Label(UVIAQI);
    週遭環境紫外線指數.Column(0);
    週遭環境紫外線指數.FontBold(true);
    週遭環境紫外線指數.FontSize(24);
    週遭環境紫外線指數.Width(-1050);
    週遭環境紫外線指數.Row(0);
    週遭環境紫外線指數.Text("紫外線指數");
    週遭環境紫外線指數.TextColor(0xE69807DF);
    垂直配置1 = new VerticalArrangement(UVIAQI);
    垂直配置1.AlignHorizontal(3);
    垂直配置1.AlignVertical(2);
    垂直配置1.BackgroundColor(0xFFFFFFFF);
    垂直配置1.Column(0);
    垂直配置1.Width(-1050);
    垂直配置1.Row(1);
    縣市名稱U = new Label(垂直配置1);
    縣市名稱U.FontBold(true);
    縣市名稱U.FontSize(24);
    縣市名稱U.Width(-1050);
    縣市名稱U.Text("縣市名稱：");
    縣市名稱U.TextColor(0xE69807DF);
    UVI = new Label(垂直配置1);
    UVI.FontBold(true);
    UVI.FontSize(30);
    UVI.Width(-1050);
    UVI.Text("UVI");
    UVI.TextColor(0xE69807DF);
    紫外線等級 = new Label(垂直配置1);
    紫外線等級.FontBold(true);
    紫外線等級.FontSize(20);
    紫外線等級.Text("紫外線等級");
    紫外線等級.TextColor(0xFFFFFFFF);
    選擇觀測站U = new ListPicker(垂直配置1);
    選擇觀測站U.BackgroundColor(0xE69807DF);
    選擇觀測站U.FontBold(true);
    選擇觀測站U.Text("選擇觀測站");
    選擇觀測站U.TextColor(0xFFFFFFFF);
    經度U = new Label(垂直配置1);
    經度U.BackgroundColor(0xE69807DF);
    經度U.FontBold(true);
    經度U.FontSize(10);
    經度U.Width(LENGTH_FILL_PARENT);
    經度U.Text("經度");
    經度U.TextColor(0xFFFFFFFF);
    緯度U = new Label(垂直配置1);
    緯度U.BackgroundColor(0xE69807DF);
    緯度U.FontBold(true);
    緯度U.FontSize(10);
    緯度U.Width(LENGTH_FILL_PARENT);
    緯度U.Text("緯度");
    緯度U.TextColor(0xFFFFFFFF);
    開啟Google地圖U = new Button(垂直配置1);
    開啟Google地圖U.BackgroundColor(0xE69807DF);
    開啟Google地圖U.FontBold(true);
    開啟Google地圖U.Text("開啟Google地圖");
    開啟Google地圖U.TextColor(0xFFFFFFFF);
    垂直配置2 = new VerticalArrangement(UVIAQI);
    垂直配置2.AlignHorizontal(3);
    垂直配置2.AlignVertical(2);
    垂直配置2.BackgroundColor(0xFFFFFFFF);
    垂直配置2.Column(1);
    垂直配置2.Width(-1050);
    垂直配置2.Row(1);
    縣市名稱A = new Label(垂直配置2);
    縣市名稱A.FontBold(true);
    縣市名稱A.FontSize(24);
    縣市名稱A.Width(-1050);
    縣市名稱A.Text("縣市名稱：");
    縣市名稱A.TextColor(0xFF00C715);
    AQI = new Label(垂直配置2);
    AQI.BackgroundColor(0xFFFFFFFF);
    AQI.FontBold(true);
    AQI.FontSize(30);
    AQI.Width(-1050);
    AQI.Text("AQI");
    AQI.TextColor(0xFF00C715);
    空氣品質等級 = new Label(垂直配置2);
    空氣品質等級.FontBold(true);
    空氣品質等級.FontSize(20);
    空氣品質等級.Text("空氣品質等級");
    空氣品質等級.TextColor(0xFFFFFFFF);
    選擇觀測站A = new ListPicker(垂直配置2);
    選擇觀測站A.BackgroundColor(0xFF00C715);
    選擇觀測站A.FontBold(true);
    選擇觀測站A.Text("選擇觀測站");
    選擇觀測站A.TextColor(0xFFFFFFFF);
    經度A = new Label(垂直配置2);
    經度A.BackgroundColor(0xFF00C715);
    經度A.FontBold(true);
    經度A.FontSize(10);
    經度A.Width(LENGTH_FILL_PARENT);
    經度A.Text("經度");
    經度A.TextColor(0xFFFFFFFF);
    緯度A = new Label(垂直配置2);
    緯度A.BackgroundColor(0xFF00C715);
    緯度A.FontBold(true);
    緯度A.FontSize(10);
    緯度A.Width(LENGTH_FILL_PARENT);
    緯度A.Text("緯度");
    緯度A.TextColor(0xFFFFFFFF);
    開啟Google地圖A = new Button(垂直配置2);
    開啟Google地圖A.BackgroundColor(0xFF00C715);
    開啟Google地圖A.FontBold(true);
    開啟Google地圖A.Text("開啟Google地圖");
    開啟Google地圖A.TextColor(0xFFFFFFFF);
    user表格 = new TableArrangement(this);
    user表格.Width(LENGTH_FILL_PARENT);
    user表格.Rows(3);
    USER溫度 = new VerticalArrangement(user表格);
    USER溫度.AlignHorizontal(3);
    USER溫度.AlignVertical(2);
    USER溫度.BackgroundColor(0xFF00FF00);
    USER溫度.Column(0);
    USER溫度.Height(-1030);
    USER溫度.Width(-1050);
    USER溫度.Row(0);
    室內溫度user = new Label(USER溫度);
    室內溫度user.FontBold(true);
    室內溫度user.FontSize(30);
    室內溫度user.Text("目前室內溫度：");
    溫度數值User = new Label(USER溫度);
    溫度數值User.FontBold(true);
    溫度數值User.FontSize(60);
    溫度數值User.Text("27°C");
    溫度數值User.TextColor(0xFFFFFFFF);
    溫度敘述User = new Label(USER溫度);
    溫度敘述User.FontBold(true);
    溫度敘述User.FontSize(60);
    溫度敘述User.Text("正常");
    溫度敘述User.TextColor(0xFFFFFFFF);
    USERaqi = new VerticalArrangement(user表格);
    USERaqi.AlignHorizontal(3);
    USERaqi.AlignVertical(2);
    USERaqi.BackgroundColor(0xC2ECEC00);
    USERaqi.Column(1);
    USERaqi.Height(-1030);
    USERaqi.Width(-1050);
    USERaqi.Row(1);
    AQI地區 = new Label(USERaqi);
    AQI地區.FontBold(true);
    AQI地區.FontSize(30);
    AQI地區.Text("台南地區空氣品質：");
    AQI等級User = new Label(USERaqi);
    AQI等級User.FontBold(true);
    AQI等級User.FontSize(60);
    AQI等級User.Text("普通");
    AQI等級User.TextColor(0xFFFFFFFF);
    AQI敘述User = new Label(USERaqi);
    AQI敘述User.FontBold(true);
    AQI敘述User.FontSize(30);
    AQI敘述User.Text("可外出活動");
    AQI敘述User.TextColor(0xFFFFFFFF);
    USERuvi = new VerticalArrangement(user表格);
    USERuvi.AlignHorizontal(3);
    USERuvi.AlignVertical(2);
    USERuvi.BackgroundColor(0xFFFFC800);
    USERuvi.Column(0);
    USERuvi.Height(-1030);
    USERuvi.Width(-1050);
    USERuvi.Row(1);
    UVI地區 = new Label(USERuvi);
    UVI地區.FontBold(true);
    UVI地區.FontSize(30);
    UVI地區.Text("台南地區紫外線：");
    UVI等級User = new Label(USERuvi);
    UVI等級User.FontBold(true);
    UVI等級User.FontSize(60);
    UVI等級User.Text("高量級");
    UVI等級User.TextColor(0xFFFFFFFF);
    UVI敘述User = new Label(USERuvi);
    UVI敘述User.FontBold(true);
    UVI敘述User.FontSize(30);
    UVI敘述User.Text("在陽光強烈時尋找遮蔽處");
    UVI敘述User.TextColor(0xFFFFFFFF);
    USER氣體 = new VerticalArrangement(user表格);
    USER氣體.AlignHorizontal(3);
    USER氣體.AlignVertical(2);
    USER氣體.BackgroundColor(0xFFFF0000);
    USER氣體.Column(1);
    USER氣體.Height(-1030);
    USER氣體.Width(-1050);
    USER氣體.Row(2);
    有害氣體偵測 = new Label(USER氣體);
    有害氣體偵測.FontBold(true);
    有害氣體偵測.FontSize(30);
    有害氣體偵測.Text("氣體偵測：");
    有害氣體狀態 = new Label(USER氣體);
    有害氣體狀態.FontBold(true);
    有害氣體狀態.FontSize(60);
    有害氣體狀態.Text("氣體濃度異常");
    有害氣體狀態.TextColor(0xFFFFFFFF);
    USER地震 = new VerticalArrangement(user表格);
    USER地震.AlignHorizontal(3);
    USER地震.AlignVertical(2);
    USER地震.BackgroundColor(0xFF00FF00);
    USER地震.Column(0);
    USER地震.Height(-1030);
    USER地震.Width(-1050);
    USER地震.Row(2);
    地震偵測 = new Label(USER地震);
    地震偵測.FontBold(true);
    地震偵測.FontSize(30);
    地震偵測.Text("地震偵測：");
    地震狀態 = new Label(USER地震);
    地震狀態.FontBold(true);
    地震狀態.FontSize(60);
    地震狀態.Text("安全");
    地震狀態.TextColor(0xFFFFFFFF);
    USER濕度 = new VerticalArrangement(user表格);
    USER濕度.AlignHorizontal(3);
    USER濕度.AlignVertical(2);
    USER濕度.BackgroundColor(0xFF00FF00);
    USER濕度.Column(1);
    USER濕度.Height(-1030);
    USER濕度.Width(-1050);
    USER濕度.Row(0);
    室內濕度user = new Label(USER濕度);
    室內濕度user.FontBold(true);
    室內濕度user.FontSize(30);
    室內濕度user.Text("目前室內濕度：");
    濕度數值User = new Label(USER濕度);
    濕度數值User.FontBold(true);
    濕度數值User.FontSize(60);
    濕度數值User.Text("65%");
    濕度數值User.TextColor(0xFFFFFFFF);
    濕度敘述User = new Label(USER濕度);
    濕度敘述User.FontBold(true);
    濕度敘述User.FontSize(60);
    濕度敘述User.Text("正常");
    濕度敘述User.TextColor(0xFFFFFFFF);
    讀取資料 = new Label(this);
    讀取資料.Text("讀取資料...");
    電話撥號器1 = new PhoneCall(this);
    電話撥號器1.PhoneNumber(975533675);
    簡訊1 = new Texting(this);
    簡訊1.Message(Emergency !!);
    簡訊1.PhoneNumber(975533675);
    藍牙客戶端1 = new BluetoothClient(this);
    GoogleForm = new Web(this);
    計時器1 = new Clock(this);
    計時器1.TimerInterval(5000);
    webUVI = new Web(this);
    webUVI.Url(http://opendata.epa.gov.tw/webapi/Data/UV/?$orderby=PublishTime%20desc&$skip=0&$top=1000&format=json);
    Activity開啟地圖 = new ActivityStarter(this);
    Activity開啟地圖.Action("android.intent.action.VIEW");
    webAQI = new Web(this);
    webAQI.Url(http://opendata.epa.gov.tw/webapi/Data/REWIQA/?$orderby=SiteName&$skip=0&$top=1000&format=json);
    GoogleFormE = new Web(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}